global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "rules/*.yml"

scrape_configs:
  - job_name: 'jarvis-nv'
    static_configs:
      - targets: ['jarvis-nv:9090']
    scrape_interval: 5s
    metrics_path: /metrics
    
  - job_name: 'ghostchain'
    static_configs:
      - targets: ['ghostchain:8545']
    scrape_interval: 10s
    metrics_path: /debug/metrics/prometheus
    
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
